#Ideia antiga não mais necessária
#UserParameter=gpu.usage,D:\Zabbix_scripts\gpu_usage.bat
#UserParameter=gpu.fanspeed,D:\Zabbix_scripts\gpu_fanspeed.bat

#Parametros para os itens e alertas de GPU NVIDIA:
#Para ter uma lista do que cada query faz: digite no terminal: nvidia-smi --help-query-gpu > nvidia-smi-query-gpu-help.txt
UserParameter=gpu.usage, nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits
UserParameter=gpu.fanspeed, nvidia-smi --query-gpu=fan.speed --format=csv,noheader,nounits
UserParameter=gpu.temperature, nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits


# Regra de Descoberta (Gera o JSON com Índice e Nome da GPU)
UserParameter=nvidia.gpu.discovery, powershell -Command "$data = nvidia-smi --query-gpu=index,name --format=csv,noheader,nounits; $list = foreach ($line in $data) { if ($line -match '(.+), (.+)') { @{ '{#GPU_INDEX}' = $matches[1].Trim(); '{#GPU_NAME}' = $matches[2].Trim() } } }; ConvertTo-Json -InputObject @($list) -Compress"

# Itens de Coleta (Recebem o índice da GPU como parâmetro $1)
UserParameter=nvidia.gpu.usage[*], nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits --id=$1
UserParameter=nvidia.gpu.fanspeed[*], nvidia-smi --query-gpu=fan.speed --format=csv,noheader,nounits --id=$1
UserParameter=nvidia.gpu.temperature[*], nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits --id=$1
